apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-pod-manager-binding
subjects:
- kind: ServiceAccount
  name: pooja-demo-sa
  namespace: "pooja-1"
#- kind: ServiceAccount
#  name: pooja-account
#  namespace: "pooja"
roleRef:
  kind: ClusterRole
  name: cluster-pod-manager
  apiGroup: rbac.authorization.k8s.io
