apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.serviceName }}
  namespace: pooja
spec:
  type: NodePort
  selector:
    name: poojatry
  ports:
    - protocol: TCP
      port: 9376
      targetPort: 7999
#      nodePort: 30475

~
