apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-file
  namespace: pooja
data:
  nginx.conf: |
    worker_processes auto;
    pid /tmp/nginx.pid;

    events {
      worker_connections 700;
    }

    http {
      default_type application/octet-stream;
      access_log /var/log/nginx/access.log;
      error_log /var/log/nginx/error.log;
      server {
        listen 7999;
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
        }
        }
      }

