apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mypsp
spec:
  privileged: false
  hostNetwork: true
  hostIPC: false
  hostPID: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - min: 0
    max: 8000
  volumes:
  - '*'
