apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pooja-role-binding
  namespace: pooja
subjects:
- kind: ServiceAccount
  name: pooja-account
roleRef:
  kind: Role
  name: pooja-role
  apiGroup: rbac.authorization.k8s.io
